name: Go

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.6.0
        with:
          fetch-depth: 0 # Retrieve all commit history, so `git rev-list --count` works correctly
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version: ^1

      - name: Vet Go code
        run: go vet ./...

      - name: Run Go tests
        run: go test -mod=readonly -v -race ./...

      - name: Verify repo is unchanged
        run: git diff --exit-code HEAD

      - name: Tag release
        if: github.ref == 'refs/heads/main'
        run: make tag-version
